name: cicd

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code
        run: echo "cloning code"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build docker
        run: echo "build docker"

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Running test cases
        run: echo "Testing the app"

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy build
        run: echo "deploy build"
