name: Auto Linter

on:
  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout/clone the code
        uses: actions/checkout@v4

      -  name: Install linter
         run: pip install ruff 

      - name: check linting
        run: ruff check .
    
